pipeline {
    agent any
    stages {
        stage('stage 1') {
            steps {
                script{
                echo "stage 1"
                    //do your things of first pipeline stage
                }
            }
        }
        stage('stage 2') {
            steps {
                script{
                sh "./gradlew spotlessCheck"
                    //do your things of first pipeline stage
                }
            }
        }
    }
}